sudo: false
language: go
go:
  - 1.9.4
  - tip
install: skip
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - goveralls -v -service travis-ci
branches:
  only:
    - master
matrix:
  allow_failures:
    - go: tip